### ISSUE TITLE
Test fail because of something I don't know

### ISSUE THREAD

**Issue by LucienShui** [PasteUs/PasteMeAdmin#11]
Source Version: [LucienShui/PasteMeAdmin@c7cab2a](https://github.com/LucienShui/PasteMeAdmin/tree/c7cab2a0c94851d7678daf4e6cc726f2c8656778)

When running `mvn test`:

```log
java.lang.ClassCastException: class com.alibaba.fastjson.JSONObject cannot be cast to class cn.pasteme.algorithm.pair.Pair (com.alibaba.fastjson.JSONObject and cn.pasteme.algorithm.pair.Pair are in unnamed module of loader 'app')
	at cn.pasteme.admin.mapper.test.AdminMapperTests.assertPairListEquals(AdminMapperTests.java:82)
	at cn.pasteme.admin.mapper.test.AdminMapperTests.riskCheckResultMapperTest(AdminMapperTests.java:136)
```

When insert [RiskCheckResultDO](https://github.com/LucienShui/PasteMeAdmin/blob/c7cab2a0c94851d7678daf4e6cc726f2c8656778/src/main/java/cn/pasteme/admin/entity/RiskCheckResultDO.java) into database, mapper [transfer](https://github.com/LucienShui/PasteMeAdmin/blob/c7cab2a0c94851d7678daf4e6cc726f2c8656778/src/main/java/cn/pasteme/admin/mapper/RiskCheckResultMapper.java#L34) `result` field into JSON string first, then save it to JSON type field in database.

But when select DO from database, the real data in `RiskCheckResultDO.result` field become `List<JSONObject>` type **instead of** `List<Pair<String, Long>>`, here is the question I have.

Here is the code: [AdminMapperTests:82](https://github.com/LucienShui/PasteMeAdmin/blob/c7cab2a0c94851d7678daf4e6cc726f2c8656778/src/test/java/cn/pasteme/admin/mapper/test/AdminMapperTests.java#L82)

Here is the runtime: [PasteUs/PasteMeAdmin/runs/286045473](https://github.com/PasteUs/PasteMeAdmin/runs/286045473)

**Comment by LucienShui** [comment]
https://github.com/LucienShui/PasteMeAdmin/commit/8ec2ab3cc128fccf79af2257fc977ae451552e8b
